# Generated by Django 3.0.2 on 2020-01-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='UXpsdoDiZmOptOMjkFgR', max_length=20, unique=True),
        ),
    ]
