# Generated by Django 3.0.2 on 2020-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200129_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='WQnTMAX7NEHgk9jpGmFK', max_length=20, unique=True),
        ),
    ]
