# Generated by Django 3.0.2 on 2020-01-29 14:31

import api.gen_slug
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200129_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 17, 31, 14, 107092)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=api.gen_slug.gen_slug, max_length=20, unique=True),
        ),
    ]
