# Generated by Django 3.0.2 on 2020-02-01 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200129_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='in_school',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 16, 7, 3, 556109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 16, 7, 3, 556109, tzinfo=utc)),
        ),
    ]
