# Generated by Django 3.0.2 on 2020-02-17 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200201_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 12, 42, 57, 679455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 12, 42, 57, 679455, tzinfo=utc)),
        ),
    ]
